### ISSUE TITLE
not really an issue

### ISSUE THREAD

**Issue by lasthom** [MizterB/RetroPie-Setup-Ubuntu#2]
first of all, i really apreciate your script it works very nice and simplifies the task of installing retropie on an headless enviroment.

I would like to have a look to this https://github.com/thebezelproject/BezelProject it is possible to add this to your script?

thx

**Comment by MizterB** [comment]
Took a while, but this fits nicely into the new "optional script" feature.  Implemented in 2ba10c1e323e8b1b0b78f28777633de419aa5dc0.

**Comment by lasthom** [comment]
Very nice ^^ thx for you time. I'll give it a try
