### ISSUE TITLE
Black Screen After Initial Boot

### ISSUE THREAD

**Issue by elliot12** [MizterB/RetroPie-Setup-Ubuntu#20]
I am using version (ubuntu-20.04.1-live-server-amd64) of Ubuntu.

I have done the commands as per the setup instructions and at the end it asked I wanted to reboot, to which I put yes.
But after rebooting (tried rebooting 5-6 times now) all I get after the initial Retropie loading bar is a black screen.

I also tried reimaging and putting a fresh copy of Ubuntu server (in case the last image had some issues), but I get to the exact same point again. 

Last night when I tried, I was once able to get the normal RetroPie home screen and play games etc, but it was only once. The other times it just sticks on the black screen. 

Anyone got any ideas?

**Comment by ryu777mtg** [comment]
What i have found to work for me is after reboot go into recovery mode and select the option for grub update grub bootloader after that reboot as normal. 

Not sure if its an issue with script

Though I still haven't figured out how to get access to Console TTY 1

Hope this helps

**Comment by Cleanshooter** [comment]
I have the same issue as OP.  I can still SSH into the system but when I'm on the main system I get nothing but a black screen, keyboard input and controllers are unresponsive (as far as I can tell).

**Comment by elliot12** [comment]
Apologies for the long delay. 

After trying the below:

Updating grub bootloader > Didn't change anything unfortunately :( 
Upgrading Ubuntu kernel (tried upgrading and downgrading) > Didn't work

I eventually went with installing the 18.04 version of Ubuntu server and it worked!!!! 

Thank you guys so much for your help. Still curious why the 20.04 results in a black screen, but as this Retropie build is for a friend, 18.04 should be just fine.
