### ISSUE TITLE
Python no longer in path

### ISSUE THREAD

**Issue by johnodon** [MizterB/RetroPie-Setup-Ubuntu#6]
I have tried the script on both 20.04.1 mini and server.  If I try to install 'mame' from the experimental packages in Retropie, I get the below error.  I had to reinstall python to get past the error.

= = = = = = = = = = = = = = = = = = = = =
Building 'mame' : MAME emulator
= = = = = = = = = = = = = = = = = = = = =

Removing additional swap
Adding 5075 MB of additional swap
Setting up swapspace version 1, size = 5 GiB (5321519104 bytes)
no label, UUID=a9d782a2-e629-4f3d-927e-4d78db137903
swapon: /home/pi/RetroPie-Setup/tmp/swap: swapon failed: Invalid argument
GCC 9 detected
makefile:1032: *** Python is not available in path.  Stop.
strip: 'mame64': No such file
Removing additional swap
/home/pi
Could not successfully build mame - MAME emulator (/home/pi/RetroPie-Setup/tmp/build/mame/mame64 not found).

**Comment by MizterB** [comment]
Interesting...were you able to confirm if Python was at least installed prior to this error?  I feel like it should have been picked up in the basic Retropie install.  Trying to determine if it is a Python install issue or something broke the PATH?

**Comment by johnodon** [comment]
> Interesting...were you able to confirm if Python was at least installed prior to this error? I feel like it should have been picked up in the basic Retropie install. Trying to determine if it is a Python install issue or something broke the PATH?

I'll perform another vanilla install of 20.04 mini and check.  I'll then manually install the bits/pieces per the instructions in my original thread (including RP) and see if anything changes.

**Comment by johnodon** [comment]
OK...results of my testing:

- Vanilla Ubuntu 20.04 mini install:  no python
- apt update/upgrade:  no python (as expected)
- Install RP as per the instructions to do so on a Debian distro:  no python
- Try to install mame via experimental packages:  fails with 'python no longer in path' error

So, this appears to be more of an RP scriptmodule problem in my book.

**Comment by MizterB** [comment]
Agreed.  Looks like the fix was recently merged in RetroPie.  Should be good now.
